### PR TITLE
Django 2 models support

### PR DESCRIPTION
**Pull request by dima-kov**
Django 2, models support

### CODE REVIEW

**Comment by alxdembo** [comment]
So... will anyone merge this?

**Comment by dima-kov** [comment]
Actually, I used my fork and it was OK - https://github.com/dima-kov/django-logtailer/

**Comment by fireantology** [comment]
I need to test it first

**Comment by dima-kov** [comment]
If you open my pull request, you will see only 1 change -> `on_delete` attribute. I don`t think it can break smth. And, I used this for more than 2 month - it was ok.

**Comment by badbye** [comment]
> I need to test it first

Hi, will you merge it and release a new version on pypi?

**Comment by fireantology** [comment]
Yes, will do this in those days.
Thanks

**Pull request merged**
