### PR TITLE
Make compatible with Django 1.9, suppress jQuery error

### PR DESCRIPTION
**Pull request by tclancy**
Adds migrations, updates `{% url %}` tags and removes references to no-longer-existing jQuery properties to hide error in Colorbox (though I'm not sure if that functionality is now working or I just made the error go away).

### CODE REVIEW

**Comment by fireantology** [comment]
Thanks, I will have a look as soon as I can.

**Comment by Wingjam** [comment]
ETA on this?

**Comment by fireantology** [comment]
I hope to put my hands on it this weekend.

**Comment by fireantology** [comment]
Ok, reworked colorbox and fixed couple of stuff. Just released 1.0 version tested up to Django 1.11 with python 3.5

**Pull request merged**
